### ISSUE TITLE
Ether shards can give "0 etherspeck"

### ISSUE THREAD

**Issue by RubberyChickens** [ratacat/enceladusgame#48]
Not sure what the intent is, but regardless of intent there is a bug.

If getting 0 etherspecks is intended, then the grammar for it should be: "You receive 0 etherspecks" rather than "You receive 0 etherspeck".

If getting 0 etherspecks is not intended, then that alone is a bug.

Image proof sent via discord. (can't add images here)

**Comment by ratacat** [comment]
Thankyou!  The server was out of specks. I'll note the grammar

**Comment by ratacat** [comment]
Syntax fixed
